spring:
  application:
    name: atomic

eureka:
  instance:
    metadata-map: 
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    eureka-server-port: 8761
    register-with-server: true
server:
  port: 0